name: Code Analysis and Dependency Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run Maven Dependency Check
        run: mvn org.owasp:dependency-check-maven:6.0.1:check

  snapshot-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install SNYK
        run: npm install -g snyk

      - name: Run SNYK Dependency Check
        run: snyk test
